name: .NET with Ollama Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Pull and run Ollama Docker container
      run: |
        docker pull ollama/ollama
        docker run -d -v ollama-local:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
        sleep 10 # Give the container time to initialize

    - name: Pull llama3.2:3b model
      run: |
        docker exec ollama ollama pull llama3.2:3b

    - name: Test prompt and check output
      run: |
        mkdir -p output
        dotnet run -- generate --model:llama3.2:3b --prompt:"Test prompt" --save:output/test_output.txt
        test -f output/test_output.txt && echo "Output file exists."

    - name: Test
      run: dotnet test --no-build --verbosity normal
